# Generated by Django 3.0.8 on 2020-08-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milksky', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delta',
            name='previousDelta',
        ),
        migrations.AddField(
            model_name='tile',
            name='delta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='milksky.Delta'),
        ),
    ]
