# Generated by Django 3.0.8 on 2020-08-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milksky', '0002_auto_20200801_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delta',
            name='newDateTime',
        ),
        migrations.RemoveField(
            model_name='delta',
            name='oldDateTime',
        ),
    ]
