# Generated by Django 3.0.8 on 2020-08-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milksky', '0003_auto_20200801_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSignups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=254)),
                ('dateSignedUp', models.DateField(auto_now=True)),
            ],
        ),
    ]
