# Generated by Django 3.0.8 on 2020-08-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milksky', '0004_reportsignups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportSignups',
            new_name='ReportSignup',
        ),
    ]
