# Generated by Django 3.0.8 on 2020-08-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milksky', '0005_auto_20200821_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsignup',
            name='dateSignedUp',
            field=models.DateTimeField(),
        ),
    ]
